from django.urls import path
from .views import (
    HomePage,
    InstituteListView,
    InstituteDetailView,
    CourseListView,
    CourseDetailView,
    SubmitReviewView,
    UserProfileView,
    StudentsListView,
    StudentDetailView,
    DiscoverView,
    CompareCoursesView,
    SaveCourseView,
    SavedCoursesView,
    AboutSkillRadarView,
    AboutDataView,
    TermsOfUseView,
    AccessibilityView,
    PrivacyCookiePolicyView,
    ContactUsView,

)

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('institutes/', InstituteListView.as_view(), name='institute_list'),
    path('institutes/<int:pk>/', InstituteDetailView.as_view(),
         name='institute_detail'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('submit_review/<int:course_id>/',
         SubmitReviewView.as_view(), name='submit_review'),
    path('profile/<str:username>/', UserProfileView.as_view(), name='user_profile'),
    path('students/', StudentsListView.as_view(), name='student_list'),
    path('students/<int:pk>/', StudentDetailView.as_view(), name='student_detail'),
    path('discover/', DiscoverView.as_view(), name='discover'),
    path('compare/', CompareCoursesView.as_view(), name='compare_courses'),
    path('save_course/<int:course_id>/',
         SaveCourseView.as_view(), name='save_course'),
    path('saved_courses/', SavedCoursesView.as_view(), name='saved_courses'),
    path('about-skill-radar/', AboutSkillRadarView.as_view(),
         name='about_skill_radar'),
    path('about-data/', AboutDataView.as_view(), name='about_data'),
    path('terms-of-use/', TermsOfUseView.as_view(), name='terms_of_use'),
    path('accessibility/', AccessibilityView.as_view(), name='accessibility'),
    path('privacy-cookie-policy/', PrivacyCookiePolicyView.as_view(),
         name='privacy_cookie_policy'),
    path('contact-us/', ContactUsView.as_view(), name='contact_us'),
]
